run:
  timeout: 10m
  tests: true

# These linter checks can be modified on a per project basis.
# Simply remove them from the enable list to disable them.
linters:
  disable-all: true
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - copyloopvar
  - decorder
  - dupl
  - dupword
  - errcheck
  - errchkjson
  - errname
  - exhaustive
  - forbidigo
  - gci
  - goconst
  - gocritic
  - godot
  - gofumpt
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - grouper
  - ineffassign
  - loggercheck
  - misspell
  - nilerr
  - nilnil
  - noctx
  - staticcheck
  - stylecheck
  - testifylint
  - thelper
  - tparallel
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - blank # blank imports
      - dot # dot imports
      - prefix(cosmossdk.io)
      - prefix(github.com/cosmos)
      - prefix(github.com/cosmos/cosmos-sdk)
      - prefix(github.com/cometbft/cometbft)
      # TODO: Replace below with '- prefix(<project-package-name>)'
      - prefix(github.com/strangelove-ventures/oss-repo-template)
  gosec:
    excludes:
      - G404 # disables checks on insecure random number source

issues:
  max-issues-per-linter: 0