# This workflow will ensure the project is tidy, buildable and all tests pass
# on every push to the main branch and on every pull request.
#
name: Build and Test

on:
  push:
    paths:
      - "**.go"
      - "go.sum"
    branches: [main, master]
  pull_request:
    paths:
      - "**.go"
      - "go.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.21
  READ_PAT: ${{ secrets.ORG_READ_PAT }}

jobs:

  # Check if the go.mod file is tidy
  tidy:
      runs-on: ubuntu-latest
      name: tidy
      steps:
      - uses: actions/checkout@v4
      
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Configure git to use PAT for reading private repositories
        run: git config --global url."https://${{ env.READ_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      
      - name: Go Mod Tidy
        run: |
          go mod tidy
          CHANGES_IN_REPO=$(git status --porcelain)
          if [[ -n "$CHANGES_IN_REPO" ]]; then
              echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff':"
              git status && git --no-pager diff
              exit 1
          fi

  # Build and compile the go project
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Configure git to use PAT for reading private repositories
        run: git config --global url."https://${{ env.READ_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Go Build
        run: go build ./...

  # Run all standard, go tests
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure git to use PAT for reading private repositories
        run: git config --global url."https://${{ env.READ_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      
      - name: Go Test
        run: go test ./...