# This workflow will validate bebuild a Go project, execute mod tidy, and run tests
# on every push to the repository.
#
name: build

on:
  push:
    paths:
      - "**.go"
      - "go.sum"
    branches: [main, master]
  pull_request:
    paths:
      - "**.go"
      - "go.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.21

jobs:

  # Check if the go.mod file is tidy
  tidy:
      runs-on: ubuntu-latest
      name: tidy
      steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: |
          go mod tidy
          CHANGES_IN_REPO=$(git status --porcelain)
          if [[ -n "$CHANGES_IN_REPO" ]]; then
              echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff':"
              git status && git --no-pager diff
              exit 1
          fi

  # Build and compile the go project
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go build ./...

  # Run all standard, go tests
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test ./...