# This workflow is designed to run interchain e2e tests on the project.
# Please modify the below configurations to ensure the workflow works
# correctly for your project.
#
name: "Interchain E2E Tests"

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    interchain-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # list names of `make` commands to run e2e tests on
                test:
                  - ictest-cosmos-chain
            fail-fast: false
        steps:
            - name: Set up Go 1.19
              uses: actions/setup-go@v3
              with:
                go-version: 1.19
            
            - name: checkout chain
              uses: actions/checkout@v3

            - name: run test
              run: make ${{ matrix.test }}